<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.1.352
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Customer Question or Comment Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'kristen@chompreno.com',
		'to' => 'kristen@chompreno.com'
	),
	'fields' => array(
		'custom_U6887' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'first + last name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'first + last name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'e-mail address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'e-mail address\' is required.',
				'format' => 'Field \'e-mail address\' has an invalid email.'
			)
		),
		'custom_U6899' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'your message',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
